<?php

namespace Database\Seeders;

use App\Models\PadelCourt;
use App\Models\Reservation;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class ReservationDemoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $member = User::firstOrCreate(
            ['email' => 'demo-member@padel.com'],
            [
                'name' => 'Demo Member',
                'password' => Hash::make('password'),
                'phone' => '081234567890',
                'address' => 'Jl. Contoh No. 1, Jakarta',
                'membership_level' => 'gold',
                'membership_starts_at' => Carbon::create(2025, 1, 1),
                'membership_expires_at' => Carbon::create(2025, 12, 31),
                'membership_notes' => 'Autogenerated demo member',
            ]
        );

        $court = PadelCourt::firstOrCreate(
            ['slug' => 'galaxy-center-court'],
            [
                'name' => 'Galaxy Center Court',
                'description' => 'Indoor premium padel court for demo data',
                'type' => 'indoor',
                'price_per_hour' => 350000,
                'max_players' => 4,
                'is_active' => true,
                'facilities' => ['Shower', 'Locker', 'Pro Shop'],
                'operational_hours' => [
                    'monday' => ['06:00', '23:00'],
                    'tuesday' => ['06:00', '23:00'],
                    'wednesday' => ['06:00', '23:00'],
                    'thursday' => ['06:00', '23:00'],
                    'friday' => ['06:00', '23:00'],
                    'saturday' => ['06:00', '23:59'],
                    'sunday' => ['06:00', '23:59'],
                ],
            ]
        );

        $slots = [
            ['day' => 5, 'start' => '09:00', 'duration' => 2, 'status' => 'confirmed'],
            ['day' => 12, 'start' => '15:00', 'duration' => 1, 'status' => 'pending'],
            ['day' => 19, 'start' => '18:00', 'duration' => 2, 'status' => 'completed'],
            ['day' => 26, 'start' => '07:00', 'duration' => 3, 'status' => 'confirmed'],
        ];

        foreach ($slots as $slot) {
            $start = Carbon::create(2025, 11, $slot['day'], ...explode(':', $slot['start']));
            $end = $start->copy()->addHours($slot['duration']);

            Reservation::firstOrCreate(
                [
                    'user_id' => $member->id,
                    'padel_court_id' => $court->id,
                    'start_time' => $start,
                ],
                [
                    'end_time' => $end,
                    'duration_hours' => $slot['duration'],
                    'price_per_hour' => $court->price_per_hour,
                    'total_price' => $slot['duration'] * $court->price_per_hour,
                    'status' => $slot['status'],
                    'notes' => 'Demo reservation generated by ReservationDemoSeeder',
                    'player_names' => 'Demo Member, Teammate',
                    'number_of_players' => 2,
                    'equipment_rental' => false,
                    'equipment_fee' => 0,
                ]
            );
        }
    }
}

